spring:
  profiles:
    active: local
  #控制台输出彩色
  output:
    ansi:
      enabled: always
  # mysql
  datasource:
#    url: jdbc:mysql://sh-cynosdbmysql-grp-fpbsi8fm.sql.tencentcdb.com:27096/zmk_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://172.20.60.23:3306/devops?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: mysql@2020
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 相关
    initial-size: 1
    min-idle: 1
    max-idle: 5
    max-wait-millis: 60000
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  kafka:
    bootstrap-servers: 172.20.60.23:9092 #指定kafka server的地址，集群配多个，中间，逗号隔开
    producer:
      # 发生错误后，消息重发的次数。
      retries: 0
      #当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
      batch-size: 16384
      # 设置生产者内存缓冲区的大小。
      buffer-memory: 33554432
    #      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
    #      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 10000
    #      key-deserializer: StringDeserializer
    #      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      # 在侦听器容器中运行的线程数。
      concurrency: 1
# port
server:
  port: @server.port@

logging:
  config: @logging.config@
---
spring:
  data:
    es:
      # es url
      url: http://172.20.60.23:9200




# mybatis 配置
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  # 加载全局的配置文件
  config_location: classpath:mybatis/mybatis-config.xml
---
#jetcache 集成使用
jetcache:
  statIntervalMinutes: 15   # 每隔多久统计信息的时长配置
  areaInCacheName: false   #是否配置前缀
  local:
    default: #默认area
      type: caffeine   #本地缓存类型
      keyConvertor: fastjson   #key的序列化转化的协议
      limit: 100              #本地缓存最大个数
      defaultExpireInMillis: 10000   #缓存的时间全局 默认值
  remote:
    default:
      type: redis.lettuce          #缓存数据库类型
      keyConvertor: fastjson
      uri:
        - redis://redis%402020@172.20.60.23:6379/  #这里支持集群配置
      valueDecoder: java
      valueEncoder: java
      poolConfig:
        maxIdle: 20
        maxTotal: 50
        minIdle: 5
      # 前缀
      keyPrefix: java-test:zmk
---
logback-config:
  #该日志路径为绝对路径
  logHomeDir: ../data1/logs